// Generated by dia2code
#ifndef SERVER__ABSTRACTSERVICE__H
#define SERVER__ABSTRACTSERVICE__H

#include <string>
#include <json/json.h>

#include "HttpStatus.h"

namespace server {

  /// class AbstractService - 
  class AbstractService {
    // Attributes
  protected:
    string pattern;
    // Operations
  public:
    AbstractService (const std::string& );
    ~AbstractService ();
    const std::string& getPattern () const;
    void setPattern (const std::string& );
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus post (const Json::Value& in, int id);
    HttpStatus put (Json::Value& out, const Json::Value& in);
    HttpStatus remove (int id);
  };

};

#endif
