// Generated by dia2code
#ifndef ENGINE__COMMANDSET__H
#define ENGINE__COMMANDSET__H


namespace engine {

  enum CommandSet {
    KEY_W     = 1,
    KEY_C     = 2,
    KEY_LEFT     = 3,
    KEY_RIGHT     = 4,
    KEY_DEFEND     = 5,
    KEY_KICK_P1     = 6,
    KEY_KICK_P2     = 7
  };

};

#endif
