// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "CommandSet.h"
#include "Action.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  public:
    state::State* currentState;
    std::vector<Action*> actions;
    // Operations
  public:
    Engine (state::State* );
    void execute (engine::CommandSet );
  };

};

#endif
