// Generated by dia2code
#ifndef ENGINE__HURT__H
#define ENGINE__HURT__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Hurt - 
  class Hurt : public engine::Action {
    // Attributes
  public:
    int id;
    // Operations
  public:
    Hurt (int );
    void apply (state::State* );
  };

};

#endif
