// Generated by dia2code
#ifndef ENGINE__KICK__H
#define ENGINE__KICK__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Kick - 
  class Kick : public engine::Action {
    // Attributes
  public:
    int id;
    // Operations
  public:
    Kick ( int);
    void apply (state::State* );
  };

};

#endif
