// Generated by dia2code
#ifndef ENGINE__MOVEPLAYER__H
#define ENGINE__MOVEPLAYER__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MovePlayer - 
  class MovePlayer : public engine::Action {
    // Operations
  public:
    MovePlayer (int );
    void apply (state::State* , int );
  };

};

#endif
