// Generated by dia2code
#ifndef ENGINE__MOVE__H
#define ENGINE__MOVE__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "state/Direction.h"
#include "Action.h"

namespace engine {

  /// class Move - 
  class Move : public engine::Action {
    // Attributes
  public:
    int  id;
    state::Direction direction;
    // Operations
  public:
    Move (int , state::Direction );
    void apply (state::State* );
  };

};

#endif
