// Generated by dia2code
#ifndef ENGINE__PUNCH__H
#define ENGINE__PUNCH__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Punch - 
  class Punch : public engine::Action {
    // Attributes
  public:
    int id;
    // Operations
  public:
    Punch (int );
    void apply (state::State* );
  };

};

#endif
