// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H


namespace render {

  /// class Animation - 
  class Animation {
    // Attributes
  public:
    float speed;
    // Operations
  public:
    Animation ();
    void setSpeed (float speed);
    void update ();
  };

};

#endif
