// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H

#include "SFML/Graphics.hpp"
#include "SFML/Graphics/Drawable.hpp"
#include "SFML/System/Time.hpp"
#include "SFML/System/Vector2.hpp"
#include "SFML/Graphics/RenderTarget.hpp"
#include "SFML/Graphics/Transformable.hpp"
#include "SFML/Window.hpp"
#include <vector>
#include <stdlib.h>

namespace render {

  /// class Animation - 
  class Animation {
    // Attributes
  private:
    std::vector<sf::IntRect> my_frames;
    const sf::Texture* my_texture;
    // Operations
  public:
    Animation ();
    void addFrame (sf::IntRect rect);
    void setSprite (const sf::Texture& texture);
    const sf::Texture *  getSprite () const;
    std::size_t  getSize () const;
    const sf::IntRect&  getFrame (std::size_t i) const;
  };

};

#endif
