// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H


namespace state {
  class StateObserver;
};
namespace render {
  class Layer;
}

#include "state/StateEvent.h"
#include "state/StateObserver.h"
#include "Layer.h"

namespace render {

  /// class Scene - 
  class Scene : public state::StateObserver {
    // Associations
    // Operations
  public:
    Scene ();
    void update ();
    void stateChanged (state::StateEvent e);
  };

};

#endif
