// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <vector>

namespace state {
  class StateObserver;
}

#include "state/StateObserver.h"

namespace render {

  /// class Scene - 
  class Scene : public state::StateObserver {
    // Attributes
  public:
    int width;
    int height;
    std::vector<Layers*> layers;
  };

};

#endif
