// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace state {
  class State;
}

namespace ai {

  /// class Ai - 
  class Ai {
    // Attributes
  public:
    state::State* state;
    // Operations
  public:
    Ai (state::State* );
    virtual void run () = 0;
  };

};

#endif
