// Generated by dia2code
#ifndef AI__DUMBAI__H
#define AI__DUMBAI__H


namespace state {
  class State;
};
namespace ai {
  class Ai;
}

#include "Ai.h"

namespace ai {

  /// class DumbAI - 
  class DumbAI : public ai::Ai {
    // Attributes
  public:
    state::State* state;
    // Operations
  public:
    DumbAI (state::State* );
    void run (state::State* );
    void run ();
  };

};

#endif
