// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace state {
  class State;
};
namespace ai {
  class Ai;
}

#include "Ai.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::Ai {
    // Attributes
  public:
    state::State * state;
    // Operations
  public:
    HeuristicAI (state::State* );
    int findBestMove ();
    void run (state::State* );
    void run ();
  };

};

#endif
