// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace state {
  class State;
};
namespace ai {
  class Ai;
}

#include "Ai.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::Ai {
    // Operations
  public:
    void run ();
    HeuristicAI (state::State* );
  };

};

#endif
