// Generated by dia2code
#ifndef STATE__COMBO__H
#define STATE__COMBO__H


namespace state {
  class Gauge;
}

#include "Gauge.h"

namespace state {

  /// class Combo - 
  class Combo : public state::Gauge {
    // Operations
  public:
    Combo ();
    ~Combo ();
  };

};

#endif
