// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <set>

namespace state {
  class Element;
}

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Attributes
  protected:
    std::set<char> list;
    // Operations
  public:
    ElementFactory ();
    ~ElementFactory ();
    Element* newInstance (char* id);
    void registerType (char id);
  };

};

#endif
