// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


#include "TypeId.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  public:
    TypeId typeId;
  protected:
    int x;
    int y;
    // Operations
  public:
    Element ();
    ~Element ();
    TypeId  getTypeId ();
    int getX ();
    int getY ();
    void setX (int x);
    void setY (int y);
    void setTypeId (TypeId t );
  };

};

#endif
