// Generated by dia2code
#ifndef STATE__GAUGE__H
#define STATE__GAUGE__H


namespace state {

  /// class Gauge - 
  class Gauge {
    // Attributes
  public:
    int volume;
    // Operations
  public:
    bool  isEmpty ();
    bool  isFull ();
    void increase (int v);
    void decrease (int v);
  };

};

#endif
