// Generated by dia2code
#ifndef STATE__HEALTH__H
#define STATE__HEALTH__H


namespace state {
  class Gauge;
}

#include "Gauge.h"

namespace state {

  /// class Health - 
  class Health : public state::Gauge {
    // Operations
  public:
    Health ();
    ~Health ();
  };

};

#endif
