// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class StateObserver;
}

#include "StateEvent.h"
#include "StateObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    mutable std::vector<StateObserver*> observers;
    // Operations
  public:
    Observable ();
    ~Observable ();
    void registerObserver (StateObserver* o);
    bool  unregisteredObserver (StateObserver* o);
    bool  notifyObservers (StateEvent e);
  };

};

#endif
