// Generated by dia2code
#ifndef STATE__PLAYEREVENT__H
#define STATE__PLAYEREVENT__H


namespace state {

  enum PlayerEvent {
    POSITION_CHANGED     = 1,
    STATUS_CHANGED     = 2,
    ATTACK_KICK     = 3,
    DEFEND     = 4,
    HEALTH_CHANGED     = 5
  };

};

#endif
