// Generated by dia2code
#ifndef STATE__PLAYERSTATUS__H
#define STATE__PLAYERSTATUS__H


namespace state {

  enum PlayerStatus {
    NORMAL     = 0,
    SUPER     = 1,
    DEAD     = 2,
    REACHABLE,
    NON_RECHABLE     = 4
  };

};

#endif
