// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include "SFML/Graphics.hpp"
#include "SFML/Graphics/Drawable.hpp"
#include "SFML/System/Time.hpp"
#include "SFML/System/Vector2.hpp"
#include "SFML/Graphics/RenderTarget.hpp"
#include "SFML/Graphics/Transformable.hpp"
#include "SFML/Window.hpp"
#include <string>
#include <vector>

namespace state {
  class Combo;
  class Health;
  class Observable;
  class Gauge;
}

#include "Combo.h"
#include "Health.h"
#include "Side.h"
#include "PlayerStatus.h"
#include "Observable.h"
#include "Gauge.h"

namespace state {

  /// class Player - 
  class Player : public state::Observable {
    // Associations
    state::Side direction;
    // Attributes
  public:
    Combo combo;
    sf::Vector2f position;
  protected:
    std::string name;
    Health health;
    std::vector<std::string> listAttack;
    Side side;
    PlayerStatus status;
    // Operations
  public:
    Player (std::string name);
    ~Player ();
    PlayerStatus getStatus ();
    void setStatus (PlayerStatus s);
    /// 	
    /// @param s		(???) 
    void setSide (Side s);
    Side getSide ();
    std::string getName ();
    /// 				
    /// @param s		(???) 
    void setName (std::string s);
    void setPosition (sf::Vector2f position);
    sf::Vector2f getPosition ();
    void notifyObservers (int i);
  };

};

#endif
