// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include "SFML/Graphics.hpp"
#include "SFML/Graphics/Drawable.hpp"
#include "SFML/System/Time.hpp"
#include "SFML/System/Vector2.hpp"
#include "SFML/Graphics/RenderTarget.hpp"
#include "SFML/Graphics/Transformable.hpp"
#include "SFML/Window.hpp"

namespace state {
  class PlayerObserver;
  class State;
  class Observable;
}

#include "PlayerStatus.h"
#include "SIDE.h"
#include "Direction.h"
#include "PlayerEvent.h"
#include "Observable.h"

namespace state {

  /// class Player - 
  class Player : public state::Observable {
    // Associations
    // Attributes
  public:
    std::string  name;
    sf::Vector2f position;
    PlayerStatus status;
    float health;
    state::SIDE side;
    state::Direction direction;
    // Operations
  public:
    Player (std::string );
    void notifyObservers (state::PlayerEvent );
    void setStatus (PlayerStatus newStatus);
    PlayerStatus getStatus () const;
    void setPosition (float , float );
    sf::Vector2f getPosition () const;
    void addObserver (PlayerObserver* );
    void link (State* );
    std::string getName () const;
    void decreaseHealth (float );
    float getHealth () const;
    state::SIDE getSide () const;
    void setDirection (state::Direction );
    state::Direction getDirection () const;
  };

};

#endif
