// Generated by dia2code
#ifndef STATE__PLAYERSTATUS__H
#define STATE__PLAYERSTATUS__H


namespace state {

  enum PlayerStatus {
    NORMAL     = 1,
    SUPER     = 2,
    DEAD     = 3
  };

};

#endif
