// Generated by dia2code
#ifndef STATE__PLAYEREVENT__H
#define STATE__PLAYEREVENT__H


namespace state {

  enum PlayerEvent {
    POSITION_CHANGED     = 1,
    STATUS_CHANGED     = 2,
    ATTACK_KICK     = 3,
    ATTACK_PUNCH     = 4,
    DEFEND     = 5,
    HEALTH_CHANGED     = 6,
    NOTHING_CHANGED     = 7,
    HURTED     = 8
  };

};

#endif
