// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementList;
  class Time;
  class Observable;
}

#include "ElementList.h"
#include "Time.h"
#include "StateEvent.h"
#include "Observable.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  protected:
    ElementList chars;
    float timeRate;
    Time timeCount;
    // Operations
  public:
    State ();
    ~State ();
    ElementList& getChars ();
    float getTimeRate ();
    Time getTime ();
    void setTimeRate (float r);
    void setTime (Time t);
    void setChars (const ElementList& list);
    void  notifyObservers (StateEvent id);
  };

};

#endif
