// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventId {
    SMTH_CHANGED     = 0,
    TIME_CHANGED     = 1,
    HEALTH_CHANGED     = 2,
    COMBO_CHANGED     = 3,
    COMBO_USED     = 3
  };

};

#endif
