// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {

  enum StateEvent {
    SMTH_CHANGED     = 0,
    TIME_CHANGED     = 1,
    HEALTH_CHANGED     = 2,
    COMBO_CHANGED     = 3,
    COMBO_USED     = 3
  };

};

#endif
