// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class Player;
  class PlayerObserver;
  class Observable;
}

#include "Observable.h"
#include "Player.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  public:
    std::vector<Player*> players;
    // Operations
  public:
    State ();
    State (Player*  , Player* );
    void notifyObservers ();
    void addObserver (PlayerObserver* );
  };

};

#endif
