// Generated by dia2code
#ifndef STATE__STATEOBSERVER__H
#define STATE__STATEOBSERVER__H


#include "StateEventId.h"

namespace state {

  /// class StateObserver - 
  class StateObserver {
    // Operations
  public:
    void stateChanged (StateEventId EventId);
  };

};

#endif
