// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class Player;
  class Observable;
}

#include "StateEvent.h"
#include "engine/CommandTypeId.h"
#include "Observable.h"
#include "Player.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  public:
    std::vector<Player*> players;
    // Operations
  public:
    State ();
    void  notifyObservers (StateEvent id);
    void setBeginningTime (float t);
    void update (engine::CommandTypeId order);
  };

};

#endif
