// Generated by dia2code
#ifndef STATE__TIME__H
#define STATE__TIME__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Time - 
  class Time : public state::Element {
    // Attributes
  public:
    int time;
    // Operations
  public:
    Time ();
    ~Time ();
    int getTime ();
    void setTime (int t);
    /// 					
    /// @param t		(???) 
    void increase (int t);
    void decrease (int t);
    void reset ();
  };

};

#endif
