// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Action.h"
#include "engine/Engine.h"
#include "engine/Move.h"
#include "engine/Punch.h"
#include "engine/Kick.h"
#endif
